In [6]:
import numpy as np
x = np.random.random((2,3))
y = 

y = 1 + np.exp(-x)
z = np.exp(x)
print y
print 1 / z


[[ 1.44309503  1.66531932  1.40316719]
 [ 1.649317    1.74939945  1.42704515]]
[[ 0.44309503  0.66531932  0.40316719]
 [ 0.649317    0.74939945  0.42704515]]


In [12]:
import numpy as np
import random

def softmax(x):

    ### YOUR CODE HERE
    
    if(len(x.shape) > 1): # matrix
        rowmax = x.max(axis = 1, keepdims = True)
        x = x - rowmax
        exp = np.exp(x)
        rowsum = exp.sum(axis = 1,keepdims = True)
        return exp / rowsum
        
        
    else:  # vector
        maxval = x.max()
        x = x - maxval
        exp = np.exp(x)
        sums = exp.sum()
        return exp / sums
      

In [13]:
import numpy as np

def sigmoid(x):
    """
    Compute the sigmoid function for the input here.
    """
    deno = 1 + np.exp(-x)
   
    return 1. / deno

def sigmoid_grad(f):
    """
    Compute the gradient for the sigmoid function here. Note that
    for this implementation, the input f should be the sigmoid
    function value of your original input x. 
    """

    right = 1 - f
    return np.multiply(f, right)
    


In [ ]:
def forward_backward_prop(data, labels, params, dimensions):
    """ 
    Forward and backward propagation for a two-layer sigmoidal network 
    
    Compute the forward propagation and for the cross entropy cost,
    and backward propagation for the gradients for all parameters.
    """

    ### Unpack network parameters (do not modify)
    ofs = 0
    Dx, H, Dy = (dimensions[0], dimensions[1], dimensions[2])

    W1 = np.reshape(params[ofs:ofs+ Dx * H], (Dx, H))
    ofs += Dx * H
    b1 = np.reshape(params[ofs:ofs + H], (1, H))
    ofs += H
    W2 = np.reshape(params[ofs:ofs + H * Dy], (H, Dy))
    ofs += H * Dy
    b2 = np.reshape(params[ofs:ofs + Dy], (1, Dy))

    ### YOUR CODE HERE: forward propagation
    
    hidden = sigmoid(data.dot(W1) + b1)
    prediction = softmax(hidden.dot(W2) + b2)
    
    
    ### END YOUR CODE
    
    ### YOUR CODE HERE: backward propagation
    raise NotImplementedError
    ### END YOUR CODE
    
    ### Stack gradients (do not modify)
    grad = np.concatenate((gradW1.flatten(), gradb1.flatten(), 
        gradW2.flatten(), gradb2.flatten()))
    
    return cost, grad